### ISSUE TITLE
Deluge Web UI No Longer Starting

### ISSUE THREAD

**Issue by GTeixeira** [mafredri/deluge-apkg#4]
After Python update to 2.7.10.r10, Deluge Web Ui no longer started.
I tried to start it manually via SSH and i'm getting this error:
"undefined symbol: _PyErr_ReplaceException"

I know it might be a python problem, but i'm hoping you can don something about it.

Thanks

**Comment by mafredri** [comment]
Hi, I've pushed an update to the App Central, but usually it takes a while for Asustor to review.

In the mean time, you can download it [from here](https://app.box.com/s/qw5ptv0uwf4k0ktyjegw80gzbsuzjyyy).

Pick the version that matches your system. AS-3 and AS-2 is i386, rest should be x86-64.

It can be installed through App Central -> Manual install

**Comment by GTeixeira** [comment]
You're wesome! Will update later at home ;) 
Thanks for your great work! 
Em 24/08/2015 2:29 da tarde, Mathias Fredriksson <notifications@github.com> escreveu:Hi, I've pushed an update to the App Central, but usually it takes a while for Asustor to review.

In the mean time, you can download it from here.

Pick the version that matches your system. AS-3 and AS-2 is i386, rest should be x86-64.

It can be installed through App Central -> Manual install
