### ISSUE TITLE
[1.3.14] Move Storage use wrong path

### ISSUE THREAD

**Issue by Pbroc** [mafredri/deluge-apkg#5]
When I use the move storage function, Deluge create the folder here:

`/volume0/usr/builtin/webman/portal/apis/appCentral/`

**EDIT: It's working with a slash before the folder, but before 1.3.14, it was working without the slash.**

**Comment by mafredri** [comment]
Could you provide some details on what you expect should happen? E.g. what's the input you used to give, and what was the result?

Nothing has really changed in the regard of the Asustor app, so it's either a change in Deluge or a change in App Central that is causing the change in behavior. But I'm surprised that it ever worked properly without a `/` in the beginning 😄.

**Comment by Pbroc** [comment]
Yeah I know, it's not very good to skip the `/`, but I guess it's just a bad habit I started to use 😄

So just to explain the issue, I tried to move a torrent in pause state, to `volume2/folder/folder` and Deluge move this path inside appCentral folder.

In conclusion, with a slash before `/volume2/`, it's works perfectly now.

**Comment by mafredri** [comment]
Hmm, I think I could make your old use-case work, but that would mean deluge has to run with its working directory set to root (`/`). I'm not entirely comfortable with that though :/, then again volume0's appCentral path isn't much better (since it's quite hidden and not a place to store things).

**Comment by Pbroc** [comment]
No, no, it's ok for me, don't change anything, and thanks for your work !

**Comment by mafredri** [comment]
Alright, glad it's OK with you. Enjoy :)!
